# Generated by Django 3.1.2 on 2020-10-09 22:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://semantic-ui.com/images/avatar/small/steve.jpg', max_length=255, verbose_name='image'),
        ),
    ]
