# Generated by Django 3.1.2 on 2020-10-09 23:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201009_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='u9acqxd8itejhuqp0pai', max_length=255, verbose_name='image'),
        ),
    ]
